-- ======================================
-- Top Customers by Number of Orders
-- Identifies customers with the highest purchase frequency
-- ======================================

select
c.id,
c.name,
count(o.id) as total_orders
from customers c
join orders o on c.id = o.customer_id
group by c.id, c.name
order by total_orders desc
limit 10;

-- ======================================
-- Top Customers by Total Spending
-- Calculates total revenue generated by each customer
-- ======================================

select
    c.id,
    c.name,
    sum(oi.price * oi.quantity) AS total_spent
from customers c
join orders o ON c.id = o.customer_id
join order_items oi ON o.id = oi.order_id
group by c.id, c.name
order by total_spent DESC
limit 10;

-- ======================================
-- Best-Selling Products
-- Shows products with the highest total quantity sold
-- ======================================

select
p.id,
p.name,
sum(oi.quantity) as total_sold
from products p
join order_items oi on p.id= oi.product_id
group by p.id, p.name
order by total_sold desc
limit 10;

-- ======================================
-- Top Revenue-Generating Products
-- Ranks products based on total revenue contribution
-- ======================================

select
p.name,
sum(oi.quantity * oi.price) as revenue
from products p
join order_items oi on p.id = oi.product_id
group by p.name
order by revenue desc
limit 10;

-- ======================================
-- Revenue by Category
-- Analyzes which product categories generate the most revenue
-- ======================================

select
c.category_name,
sum(oi.quantity * oi.price) as total_revenue
from categories c
join products p on c.id= p.category_id
join order_items oi on p.id = oi.product_id 
group by c.category_name
order by total_revenue desc;

-- ======================================
-- Average Order Value (AOV)
-- Calculates the average revenue per order
-- ======================================

select
avg(order_total) as avg_order_value
from(
select
o.id,
sum(oi.price * oi.quantity) as order_total
from orders o
join order_items oi on o.id = oi.order_id
group by o.id
)t;


-- ======================================
-- Customer Activity (Recency Analysis)
-- Finds the most recently active customers
-- ======================================

select
c.name,
max(o.order_date) as last_order
from customers c
join orders o on c.id = o.customer_id
group by c.name
order by last_order desc;


-- ======================================
-- Customer Segmentation
-- Classifies customers into segments based on order count
-- ======================================

select
c.name,
count(o.id) as total_orders,
case
	when count(o.id) > 10 then 'VIP'
	when count(o.id) > 5 then 'Regular'
	else 'New'
end as segment
from customers c
join orders o on c.id= o.customer_id
group by c.name;

-- ======================================
-- Customer Ranking by Total Spending
-- Ranks customers based on total revenue using window function
-- ======================================

Select
    c.name,
    sum(oi.price * oi.quantity) as total_spent,
    rank() over (order by sum(oi.price * oi.quantity) desc) as ranking
from customers c
join orders o ON c.id = o.customer_id
join order_items oi ON o.id = oi.order_id
group by c.name;